# Generated by Django 4.2.21 on 2025-05-21 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraEvent',
            fields=[
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extra', serialize=False, to='schedule.event')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
                ('lesson_type', models.CharField(blank=True, choices=[('yoga', 'Йога'), ('box', 'Бокс'), ('run', 'Бег')], max_length=30, verbose_name='Тип занятия')),
            ],
        ),
    ]
