# Generated by Django 4.2 on 2025-05-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraEvent',
            fields=[
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extra', serialize=False, to='schedule.event')),
                ('drugs', models.CharField(default='extraevent', max_length=250, verbose_name='Название лекарства')),
                ('dose', models.CharField(default='0', max_length=250, verbose_name='Доза')),
            ],
        ),
    ]
