# Generated by Django 4.2 on 2025-05-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('events', '0003_alter_extraevent_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraevent',
            name='base',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extraevent', serialize=False, to='schedule.event'),
        ),
    ]
