# Generated by Django 3.2.20 on 2025-06-06 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_extraevent_color'),
        ('events', '0004_alter_extraevent_base'),
    ]

    operations = [
    ]
